### ISSUE TITLE
Error in run with tensorflow

### ISSUE THREAD

**Issue by AIAdventures** [oswaldoludwig/Eigenvalue-Decay-Regularizer-for-Keras#2]
Hi, was trying to test your code.

i was getting errors though.

andrewcz@andrewcz-PORTEGE-Z30t-B ~/Eigenvalue-Decay-Regularizer-for-Keras $ python example.py 
Using TensorFlow backend.
60000 train samples
10000 test samples
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "example.py", line 64, in <module>
    metrics=['accuracy'])
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/keras/models.py", line 553, in compile
    **kwargs)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/keras/engine/training.py", line 641, in compile
    total_loss = r(total_loss)
  File "/home/andrewcz/Eigenvalue-Decay-Regularizer-for-Keras/EigenvalueDecay.py", line 57, in __call__
    domin_eigenvect = K.dot(WW, o)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 340, in dot
    if ndim(x) is not None and (ndim(x) > 2 or ndim(y) > 2):
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 220, in ndim
    dims = x.get_shape()._dims
AttributeError: 'numpy.ndarray' object has no attribute 'get_shape'

help please.
Many thanks,
Andrew

**Comment by oswaldoludwig** [comment]
Hi Andrew,

This code is only for Theano backend, a version for both Theano and
TensorFlow backends was available in Keras, but was removed in the new
version of Keras:
https://github.com/fchollet/keras/commit/1c630c3e3c8969b40a47d07b9f2edda50ec69720

You can try to run my code using Theano backend, but I'm not sure if it
will work with the current version of Keras, because I didn't upgrade my
version of Keras yet.

Best regards,

Oswaldo

2017-04-26 6:25 GMT+02:00 AIAdventures <notifications@github.com>:

**Comment by avinashkd44** [comment]
pip install git+git://github.com/avinashkd44/keras.git --upgrade  # You will get here eigenvaluedecay regularizer for tensorflow backend.

Hi Andrew and Oswaldo
I have tested and modified your file and now its working for Tensor flow  for mine.
